# This is a basic workflow to help you get started with Actions

name: CI-Dev

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ developement ]
  pull_request:
    branches: [ developement ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build project
        run: dotnet build

      # Runs a set of commands using the runners shell
      - name: publish project
        run: dotnet publish
          
      # Artifact 
      - name: Upload DevArtifact Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DevArtifact
          path: /home/runner/work/ci_cd/ci_cd/bin/Debug/netcoreapp3.1/publish/   
    
   
